### ISSUE TITLE
No speed difference with sage attention on flux?

### ISSUE THREAD

**Issue by TheDuckingDuck** [blepping/ComfyUI-bleh#13]
Heya, I thought I had sage attention working. I've set it up similar to the screenshots I've seen 
![image](https://github.com/user-attachments/assets/41cbe055-64f9-4152-a981-f9b9193b73bd)
But even with verbose enabled, I can't see any evidence that it does anything.
Speed wise, the inference speed appears exactly the same:
![image](https://github.com/user-attachments/assets/8e70f8b4-3092-47c3-9d94-bffa17758b70)
First one is with the settings in the image, 2nd one with the node disconnected, 3rd one with empty yaml.

Am I doing anything wrong? I compiled version 2.0 from their github for this, but even using the pip release things are the same, though I do have to change "sageattn_function: sageattn_qk_int8_pv_fp8_cuda" to just "sageattn_function: sageattn" for that version to not throw an error.

Hell, even using the earlier version of the node, https://gist.github.com/blepping/fbb92a23bc9697976cc0555a0af3d9af , I do not notice any speedup.

I am using a 3090 btw. Here's the full workflow, in case that helps: [Image Generation.json](https://github.com/user-attachments/files/17998814/Image.Generation.json)

**Comment by blepping** [comment]
As mentioned in the README, out of image models ComfyUI supports, it probably only works with SDXL. So you didn't do anything wrong in terms of setup, it just probably won't work with Flux. If you don't see messages at all, then Flux may not even be using ComfyUI's normal optimized attention implementation.

Whether something is supported or not comes down to whether SageAttention itself is compatible with the model (uses one of the currently supported head sizes - 64, 96 or 128) and uses the default optimized attention.

>  I've set it up similar to the screenshots I've seen

I posted that, just as an example of how you could pass parameters if you needed to. Even if SageAttention did work with Flux, that stuff would likely break it.

**Comment by TheDuckingDuck** [comment]
Gotcha, I kinda glanced over the readme and never got to the part talking about sage attention. I tried to manually hack it in and comfy just explodes at me so maybe it is completely incompatible.

**Comment by blepping** [comment]
@TheDuckingDuck I found an issue that was preventing SageAttention from applying to some models like Flux. Just pushed some changes that should fix that issue so it may be worth trying again. SageAttention 2.0.1 recently came out, I recommend using that version (the latest as of this post, but anything later should also be good).

It didn't seem like it made a huge difference to performance for Flux but it should at least do _something_ now.

**Comment by EricBCoding** [comment]
Thank you @blepping!

I managed to get SageAttention installed on Windows and, in my case, the speedup was definitely worth the hassle.

Flux Dev inference is approximately **0.25s faster per step** with these specs:

- 1152x1536 image, DDIM sampler
- nVidia GeForce 3090
- SageAttention 1.0.6

I use a distillation LoRA stack such that images converge in only 4-8 steps, but that's still 1-2 seconds saved per generation. It adds up. I imagine if you're making stuff the conventional way with 20+ steps and/or at super high resolution, SageAttention is going to provide even more savings. And the quality loss is barely noticeable.

Flux needs all the help it can get, speed-wise 🙂
