### ISSUE TITLE
Error interaction between Kohya Deep Shrink (bleh) and tinyterra pipeKSamplerSDXL

### ISSUE THREAD

**Issue by times12** [blepping/ComfyUI-bleh#8]
Hi,

Sorry new to github but your fadeout has seemed to work great so I thought I'd report this issue since I updated post-patch.

Whenever the Start Fadeout percent is triggered I get the below error, if I set it to 1, it works fine (and if its set to 0.4 it will work right upto that point).

ttN pipeKSamplerSDXL_v2
type Tensor doesn't define __round__ method

Is this more a limitation of tinyterra? I have no python knowledge so im clueless.

**Comment by blepping** [comment]
could you include the full error (traceback) please? that's a very weird error, not really sure how it could even occur.

also thank for the kind words, glad you're finding the node useful! reporting issues like this is always welcome, even if it turns out not to be a problem in my nodes specifically i might be able to add a workaround.

**Comment by times12** [comment]
I've attached for tinyterra and EasyUse nodes (Same Tensor error, but I ran them seperately as they have their own respective loaders/samplers).

I dont actually know a non-pipe workflow to pass through the model input. I dont know if you have a suggested one to test.

[Easyuse node.txt](https://github.com/user-attachments/files/16841451/Easyuse.node.txt)
#
[tinyterrapipe error.txt](https://github.com/user-attachments/files/16841443/tinyterrapipe.error.txt)

**Comment by blepping** [comment]
@times12 thanks for including that information! actually was a very dumb error on my part which would cause it to fail with any sampler as long as fadeout was enabled. apparently i didn't remember to test it after making changes, sorry for the inconvenience.

i just pushed a change that should fix it. please update and give it another try.

**Comment by times12** [comment]
Ah, that does indeed work. Thanks again for the work you do 👍

**Comment by blepping** [comment]
no problem! feel free to open another issue if you run into further problems or start a discussion to ask questions about how to do stuff.
